#index
theme:  minima
title:  Deep Learning Diary
future:  true

defaults:
  -
    scope:
      path:  "" #all files in project
      type:  "posts"
    values:
      layout:  post
      author:  Elliot 

##header navigation
header_pages:
  - index.md
  - projects.html
  - about.md
#feed.xml
name:  Lessons from Deep Learning
description:  Devlogs, tutorials, and notes on deep learning!
url:  https://nurriol2.github.io/deep-learning-diary/