#index
theme:  minima
title:  Deep Learning Diary
future:  true

##header navigation
header_pages:
  - index.md
  - projects.md
  - about.md
#feed.xml
name:  Lessons from Deep Learning
description:  One place for tutorials, notes, and projects about deep learning!
url:  https://nurriol2.github.io/deep-learning-diary/