#index
title:  Deep Learning Diary

##header navigation
header_pages:
  - index.md
  - about.md
  - projects.md
#feed.xml
name:  Lessons from Deep Learning
description:  Devlogs, tutorials, and notes on deep learning!
url:  https://nurriol2.github.io/deep-learning-diary/

plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark